name: "System Tests (Fork)"

on:
  pull_request:
    branches:
      - dest

jobs:
  test:
    uses: assaf758-dev/mlrun/.github/workflows/test-reusable.yml@dest
    with:
      message: "PR ${{ github.event.pull_request.number }} triggered"
