name: Test Reusable

on:
  workflow_call:
    inputs:
      pr_number:
        type: string
        default: ''

  workflow_dispatch:
    inputs:
      pr_number:
        description: 'PR number'
        required: false
        default: ''

jobs:
  echo-job:
    runs-on: ubuntu-latest
    steps:
      - run: echo "PR=${{ inputs.pr_number }}"
